require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/category_payments', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # CategoryPayment. As you add validations to CategoryPayment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      CategoryPayment.create! valid_attributes
      get category_payments_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      category_payment = CategoryPayment.create! valid_attributes
      get category_payment_url(category_payment)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_category_payment_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      category_payment = CategoryPayment.create! valid_attributes
      get edit_category_payment_url(category_payment)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new CategoryPayment' do
        expect do
          post category_payments_url, params: { category_payment: valid_attributes }
        end.to change(CategoryPayment, :count).by(1)
      end

      it 'redirects to the created category_payment' do
        post category_payments_url, params: { category_payment: valid_attributes }
        expect(response).to redirect_to(category_payment_url(CategoryPayment.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new CategoryPayment' do
        expect do
          post category_payments_url, params: { category_payment: invalid_attributes }
        end.to change(CategoryPayment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post category_payments_url, params: { category_payment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested category_payment' do
        category_payment = CategoryPayment.create! valid_attributes
        patch category_payment_url(category_payment), params: { category_payment: new_attributes }
        category_payment.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the category_payment' do
        category_payment = CategoryPayment.create! valid_attributes
        patch category_payment_url(category_payment), params: { category_payment: new_attributes }
        category_payment.reload
        expect(response).to redirect_to(category_payment_url(category_payment))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        category_payment = CategoryPayment.create! valid_attributes
        patch category_payment_url(category_payment), params: { category_payment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested category_payment' do
      category_payment = CategoryPayment.create! valid_attributes
      expect do
        delete category_payment_url(category_payment)
      end.to change(CategoryPayment, :count).by(-1)
    end

    it 'redirects to the category_payments list' do
      category_payment = CategoryPayment.create! valid_attributes
      delete category_payment_url(category_payment)
      expect(response).to redirect_to(category_payments_url)
    end
  end
end
